config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create]

  resources :items, only: [:show, :new]
  resources :ownerships, only: [:create, :destroy]
  
  get 'rankings/want', to: 'rankings#want'
  get 'rankings/have', to: 'rankings#have'
  
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-muted">© 2016 MONOLIST.</div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-left" href="/"><img src="/images/logo.png" alt="Monolist"></a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <%#アイテム情報 item_controller%>
              <%= link_to new_item_path do %>
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                アイテムを追加
              <% end %>
            </li>
            
            <%#ランキングの追加%>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-signal" aria-hidden="true"></span>
                ランキング
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Wantランキング', rankings_want_path %></li>
                <li><%= link_to 'Haveランキング', rankings_have_path %></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="gravatar">
                  <img src="<%= gravatar_url(current_user, size: 20) %>" alt="" class="img-circle">
                </span>
                <%= current_user.name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'マイページ', user_path(current_user) %>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to '新規登録', signup_path %></li>
            <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Monolist</title>
    <%= csrf_meta_tags %>

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
    <!-- app/assets/stylesheets -->
    <%# app/assets/stylesheets/application.css にコーディングされた CSS が読み込まれる設定%>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- app/assets/javascripts-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap JavaScript-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%# toppages.index.html参考%>
    <%= render 'layouts/navbar' %>

    <%#呼び出す側の View (app/views/toppages/index.html.erb 等) で%>
    <%#content_for :cover で定義され、その内容がその位置に埋め込まれるというだけ%>
    <%= yield :cover %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>